SlipJaq: SlipJaq
SlipJaq
Sliding login panel using jQuery.
Internal functions
_slpjq_path_begins_with ($prefix, $path)
Return TRUE if the given path begins with the specified prefix.
slpjq_admin ()
Return the form for our settings page.
slpjq_get_config_form ()
Return the configuration form for admin/settings and block configuration.
slpjq_get_path ($relpath)
Return a full path, given a path relative to our module directory.
slpjq_path_begins_with ($prefix, $path=NULL)
Return TRUE if the given path or its unaliased path begins with the specified prefix.
slpjq_redirect_form_if_errors ($form, $redirect=NULL)
Redirect the form, overriding whatever redirect was already there.
slpjq_slider_allowed_here ()
Determine whether or not the current page gets a SlipJaq slider.
slpjq_slider_render ()
Render the HTML for the slider.
Hook functions
The interfaces and semantics to these functions are documented as part of the Drupal API, as the hook_* functions.
slpjq_block ($op= 'list', $delta=0, $edit=array())
Implementation of hook_block().
slpjq_footer ($is_front=FALSE)
Implementation of hook_footer().
slpjq_form_user_login_block_alter (&$form, &$form_state)
Implementation of hook_form_user_login_block_alter().
slpjq_form_user_register_alter (&$form, &$form_state)
Implementation of hook_form_user_register_alter().
slpjq_help ($path, $arg)
Implementation of hook_help().
slpjq_init ()
Implementation of hook_init().
slpjq_menu ()
Implementation of hook_menu().
slpjq_theme ()
Implementation of hook_theme().
Callback functions
The interfaces and semantics to these functions are documented as part of the Drupal API, as callback functions.
slpjq_form_user_login_block_validate ($form, &$form_state)
Redirect to the login page if there were login form errors.
slpjq_form_user_register_validate ($form, &$form_state)
Redirect to the registration page if there were registration form errors.
Installation hook functions
slpjq_install ()
Implementation of hook_install().
slpjq_uninstall ()
Implementation of hook_uninstall().
Installation internal functions
slpjq_install_get_config_form ()
Load up our full module and invoke slpjq_get_config_form().
Detailed Description
Sliding login panel using jQuery.
See README.txt for module usage information.
 The HTML, CSS and JavaScript is based on a work by Jérémie Tisseau:
 http://web-kreation.com/index.php/tutorials/nice-clean-sliding-login-panel-built-with-jquery/
 © 2010 teeny-tiny websites
 http://www.teenytinywebsites.com
 Distributed under the terms of the GNU General Public License, version 3.0
 http://www.gnu.org/licenses/gpl-3.0.html
Function Documentation
_slpjq_path_begins_with ($ prefix, $ path)
Return TRUE if the given path begins with the specified prefix.
Definition at line 225 of file slpjq.module.
Referenced by slpjq_path_begins_with().
{
  return (($path == $prefix) || (drupal_substr($path, 0, drupal_strlen($prefix)+1) == ($prefix . '/')));
}
slpjq_admin ()
Return the form for our settings page.
Definition at line 217 of file slpjq.module.
References slpjq_get_config_form().
                       {
  return system_settings_form(slpjq_get_config_form());
}
slpjq_block ($ op = 'list', $ delta = 0, $ edit = array())
Implementation of hook_block().
Definition at line 88 of file slpjq.module.
References slpjq_get_config_form(), and slpjq_slider_render().
{
  if ($op == 'list') {
    return array(array(
        'info' => t('SlipJaq - Sliding login panel using jQuery'),
        'cache' => BLOCK_CACHE_PER_USER,
        'visibility' => 0, // This item is not displayed on the pages in the following list.
        'pages' => variable_get('slpjq_disallowed_paths', array()),
        ),
      );
  }
  elseif ($op == 'configure') {
    $form = slpjq_get_config_form();
    // Don't present the full-page option on the block configuration screen.
    unset($form['slpjq_display_top']);
    return $form;
  }
  elseif ($op == 'save') {
    $form = slpjq_get_config_form();
    // Turn off the top display if the block is edited.
    // (Yes, this might be confusing, but not as confusing if *both* are selected.)
    variable_set('slpjq_display_top', FALSE);
    unset($form['slpjq_display_top']);
    foreach ($form as $field => $v) {
      variable_set($field, $edit[$field]);
    }
  }
  elseif ($op == 'view') {
    return array(
      'content' => slpjq_slider_render(),
      );
  }
  else {
    return NULL;
  }
}
slpjq_footer ($ is_front = FALSE)
Implementation of hook_footer().
This is where we insert the page-top version of the slider.
Definition at line 146 of file slpjq.module.
References slpjq_slider_allowed_here(), and slpjq_slider_render().
{
  if (variable_get('slpjq_display_top', FALSE) && slpjq_slider_allowed_here()) {
    return slpjq_slider_render();
  }
}
slpjq_form_user_login_block_alter (&$ form, &$ form_state)
Implementation of hook_form_user_login_block_alter().
See also:
slpjq_form_user_login_block_validate()
Definition at line 158 of file slpjq.module.
{
  $form['links'] = array();     // Remove the "create new account" & "send pw reminder" links.
  $form['#action'] = url('user', array('query' => drupal_get_destination()));
  $form['#validate'][] = 'slpjq_form_user_login_block_validate';
}
slpjq_form_user_login_block_validate ($ form, &$ form_state)
Redirect to the login page if there were login form errors.
See also:
slpjq_form_user_login_block_alter()
Definition at line 192 of file slpjq.module.
References slpjq_redirect_form_if_errors().
{
  slpjq_redirect_form_if_errors($form, 'login');
}
slpjq_form_user_register_alter (&$ form, &$ form_state)
Implementation of hook_form_user_register_alter().
See also:
slpjq_form_user_register_validate()
Definition at line 170 of file slpjq.module.
{
  $form['submit']['#value'] = variable_get('slpjq_create_button_text', '');
  $form['#action'] = url('user/register', array('query' => drupal_get_destination()));
  $form['#validate'][] = 'slpjq_form_user_register_validate';
}
slpjq_form_user_register_validate ($ form, &$ form_state)
Redirect to the registration page if there were registration form errors.
See also:
slpjq_form_user_register_alter()
Definition at line 202 of file slpjq.module.
References slpjq_redirect_form_if_errors().
{
  slpjq_redirect_form_if_errors($form, 'user/register');
}
slpjq_get_config_form ()
Return the configuration form for admin/settings and block configuration.
We also use this function during installation to set the initial values of our configuration variables.
Drupal variables - We define these Drupal variables for our configuration. See the in-line definitions for details.
slpjq_display_top
slpjq_title
slpjq_image_url
slpjq_slide_period
slpjq_create_button_text
slpjq_disallowed_paths
Definition at line 316 of file slpjq.module.
Referenced by slpjq_admin(), slpjq_block(), and slpjq_install_get_config_form().
{
  static $config_form;
  if (!isset($config_form)) {
    $config_form = array( //! <strong>Drupal variables</strong> - We define these Drupal
                          //! variables for our configuration. See the in-line definitions
                          //! for details.
      'slpjq_display_top' => array( //! - slpjq_display_top
      // - slpjq_display_top
        '#type' => 'checkbox',
        '#title' => t('Display at page top'),
        '#description' => t('Display above all regions of the page at the full width of the browser window. (Never displays on admin pages.)'),
        '#default_value' => variable_get('slpjq_display_top', TRUE),
        ),
      'slpjq_title' => array( //! - slpjq_title
        '#type' => 'textfield',
        '#title' => t('Slider title'),
        '#size' => 40,
        '#maxlength' => 128,
        '#description' => t('The title that appears on the left side of the slider.'),
        '#default_value' => variable_get('slpjq_title', variable_get('site_name', '')),
        ),
      'slpjq_image_url' => array( //! - slpjq_image_url
        '#type' => 'textfield',
        '#title' => t('Slider image URL'),
        '#size' => 60,
        '#maxlength' => 128,
        '#description' => t('The URL of an image to display below the slider title. Leave blank for none. Normally begins with a slash (<strong>/</strong>) or <strong>http://</strong>.'),
        '#default_value' => variable_get('slpjq_image_url', ''),
        ),
      'slpjq_slide_period' => array( //! - slpjq_slide_period
        '#type' => 'textfield',
        '#title' => t('Slide period'),
        '#size' => 4,
        '#maxlength' => 4,
        '#description' => t('The time period, in milliseconds, that it takes for the slider to slide up or down.'),
        '#default_value' => variable_get('slpjq_slide_period', 300),
        ),
      'slpjq_create_button_text' => array( //! - slpjq_create_button_text
        '#type' => 'textfield',
        '#title' => t('Text on &ldquo;Create new account&rdquo; button'),
        '#size' => 40,
        '#maxlength' => 128,
        '#description' => t('The text on the submit button for the form that creates a new account.'),
        '#default_value' => variable_get('slpjq_create_button_text', t('Create new account')),
        ),
      'slpjq_disallowed_paths' => array( //! - slpjq_disallowed_paths
        '#type' => 'textarea',
        '#title' => t('Paths where not to display to anonymous users'),
        '#size' => 40,
        '#maxlength' => 128,
        '#description' => t('Enter one page per line as Drupal paths. When the slider is in a block, this restriction is <em>in addition to</em> any block restrictions. Wildcards are not recognized here.'),
        '#default_value' =>
          variable_get('slpjq_disallowed_paths',
            implode("\n", array(
              'login',
              'user',
              'user/password',
              'user/register',
              ))
            ),
        ),
      );
  }
  return $config_form;
}
slpjq_get_path ($ relpath)
Return a full path, given a path relative to our module directory.
Definition at line 246 of file slpjq.module.
Referenced by slpjq_init(), and slpjq_theme().
{
  static $slpjq_path;
  if (!isset($slpjq_path)) {
    $slpjq_path = drupal_get_path('module', 'slpjq');
  }
  return $slpjq_path . '/' . $relpath;
}
slpjq_help ($ path, $ arg)
Implementation of hook_help().
Definition at line 59 of file slpjq.module.
{
  if ($path == 'admin/help#slpjq') {
    $description = t('Sliding login panel using jQuery');
    return
      '<div class="slpjq-help"><p>' .
      t('Sliding login panel using jQuery') .
      '</p></div>';
  }
}
slpjq_init ()
Implementation of hook_init().
Definition at line 129 of file slpjq.module.
References slpjq_get_path(), and slpjq_slider_allowed_here().
                      {
  if (slpjq_slider_allowed_here()) {
    drupal_add_css(slpjq_get_path('css/slpjq.css'));
    // only add the JavaScript when the dynamic slider is active.
    if (!user_is_logged_in()) {
      drupal_add_js(array('slpjq' => array('slidePeriod' => variable_get('slpjq_slide_period', ''))), 'setting');
      drupal_add_js(slpjq_get_path('js/slpjq.js'));
    }
  }
}
slpjq_install ()
Implementation of hook_install().
To maximize code reusability, we simply pull in our admin configuration form, which contains all of our variable names and defaults.
Definition at line 34 of file slpjq.install.
References slpjq_install_get_config_form().
{
  $form = slpjq_install_get_config_form();
  foreach ($form as $field => $attrs) {
    variable_set($field, $attrs['#default_value']);
  }
}
slpjq_install_get_config_form ()
Load up our full module and invoke slpjq_get_config_form().
Definition at line 64 of file slpjq.install.
References slpjq_get_config_form().
Referenced by slpjq_install(), and slpjq_uninstall().
{
  if (!function_exists('slpjq_get_config_form')) {
    require_once('slpjq.module');
  }
  return slpjq_get_config_form();
}
slpjq_menu ()
Implementation of hook_menu().
Definition at line 73 of file slpjq.module.
                      {
  return array('admin/settings/slpjq' => array(
    'title' => 'SlipJaq',
    'description' => 'SlipJaq configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('slpjq_admin'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    ));
}
slpjq_path_begins_with ($ prefix, $ path = NULL)
Return TRUE if the given path or its unaliased path begins with the specified prefix.
Definition at line 233 of file slpjq.module.
References _slpjq_path_begins_with().
Referenced by slpjq_slider_allowed_here().
{
  if ($path === NULL) {
    $path = request_uri();
  }
  return
    _slpjq_path_begins_with($prefix, $path) ||
    _slpjq_path_begins_with($prefix, drupal_get_normal_path($path));
}
slpjq_redirect_form_if_errors ($ form, $ redirect = NULL)
Redirect the form, overriding whatever redirect was already there.
Definition at line 302 of file slpjq.module.
Referenced by slpjq_form_user_login_block_validate(), and slpjq_form_user_register_validate().
{
  if (form_get_errors()) {
    unset($_REQUEST['destination']);
    drupal_redirect_form($form, $redirect);
  }
}
slpjq_slider_allowed_here ()
Determine whether or not the current page gets a SlipJaq slider.
If the slider is displayed as a block, this restriction is in addition to any block restrictions
Definition at line 261 of file slpjq.module.
References slpjq_path_begins_with().
Referenced by slpjq_footer(), and slpjq_init().
{
  static $slpjq_slider_allowed_here;
  if (isset($slpjq_slider_allowed_here)) {
    return $slpjq_slider_allowed_here;
  }
  $slpjq_slider_allowed_here = FALSE;
  if (user_is_logged_in()) {
    // While logged in, we don't display on admin paths.(This is not configurable.)
    if (slpjq_path_begins_with('/admin')) {
      return FALSE;
    }
  }
  else {
    // While logged out, we don't display on these "disallowed" paths.
    foreach (explode("\n", variable_get('slpjq_disallowed_paths', array())) as $path) {
      if (slpjq_path_begins_with('/'. rtrim($path))) {
        return FALSE;
      }
    }
  }
  $slpjq_slider_allowed_here = TRUE;
  return TRUE;
}
slpjq_slider_render ()
Render the HTML for the slider.
Definition at line 289 of file slpjq.module.
Referenced by slpjq_block(), and slpjq_footer().
{
  static $already_rendered;
  if (!isset($already_rendered)) {
    $already_rendered = TRUE;
    return theme('slpjq_slider');
  }
  return '';    // We don't render this more than once per page.
}
slpjq_theme ()
Implementation of hook_theme().
Definition at line 40 of file slpjq.module.
References slpjq_get_path().
                       {
  return array(
    'slpjq_slider' => array(
      'arguments' => array(
        'logged_in' => user_is_logged_in(),
        'title' => variable_get('slpjq_title', ''),
        'image_url' => variable_get('slpjq_image_url', ''),
        'user_register' => variable_get('user_register', 1),
        ),
      'template' => 'slpjq-slider',
      'path' => slpjq_get_path('theme'),
    ),
  );
}
slpjq_uninstall ()
Implementation of hook_uninstall().
We use the same reusability technique as we did above with slpjq_install().
Definition at line 48 of file slpjq.install.
References slpjq_install_get_config_form().
{
  $form = slpjq_install_get_config_form();
  foreach ($form as $field => $attrs) {
    variable_del($field);
  }
}